export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILED = "FETCH_ACCOUNT_FAILED";

export const FETCH_ORDER_OF_ACCOUNT_SUCCESS = "FETCH_ORDER_OF_ACCOUNT_SUCCESS";
export const FETCH_ORDER_OF_ACCOUNT_FAILED = "FETCH_ORDER_OF_ACCOUNT_FAILED";

export const FETCH_FAVORITES_OF_ACCOUNT_SUCCESS =
   "FETCH_FAVORITES_OF_ACCOUNT_SUCCESS";
export const FETCH_FAVORITES_OF_ACCOUNT_FAILED =
   "FETCH_FAVORITES_OF_ACCOUNT_FAILED";
