export const FETCH_AUTH = "FETCH_AUTH";
export const FETCH_AUTH_SUCCESS = "FETCH_AUTH_SUCCESS";
export const FETCH_AUTH_FAILED = "FETCH_AUTH_FAILED";

export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS";
export const FETCH_REGISTER_FAILED = "FETCH_REGISTER_FAILED";

export const FETCH_VERIFY_EMAIL_SUCCESS = "FETCH_VERIFY_EMAIL_SUCCESS";
export const FETCH_VERIFY_EMAIL_FAILED = "FETCH_VERIFY_EMAIL_FAILED";

export const FETCH_FORGOT_PASSWORD_STEP1_SUCCESS =
   "FETCH_FORGOT_PASSWORD_STEP1_SUCCESS";
export const FETCH_FORGOT_PASSWORD_STEP1_FAILED =
   "FETCH_FORGOT_PASSWORD_STEP1_FAILED";

export const FETCH_FORGOT_PASSWORD_STEP2_SUCCESS =
   "FETCH_FORGOT_PASSWORD_STEP2_SUCCESS";
export const FETCH_FORGOT_PASSWORD_STEP2_FAILED =
   "FETCH_FORGOT_PASSWORD_STEP2_FAILED";

export const ENCRYPTCODE = "ithoangtansecurity";
//SAU NÀY NHỚ SỬA THÀNH process.env.ENCRYPTCODE
//tốt nhất là chứa trong config
