export const FETCH_EVALUATE_GET_BYID_TOUR = "FETCH_EVALUATE_GET_BYID_TOUR";

export const FETCH_EVALUATE_GET_BYID_TOUR_SUCCESS =
   "FETCH_EVALUATE_GET_BYID_TOUR_SUCCESS";

export const FETCH_EVALUATE_GET_BYID_TOUR_FAILED =
   "FETCH_EVALUATE_GET_BYID_TOUR_FAILED";

export const FETCH_POST_EVALUATE_SUCCESS = "FETCH_POST_EVALUATE_SUCCESS";

export const FETCH_POST_EVALUATE_FAILED = "FETCH_POST_EVALUATE_FAILED";
