export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";

export const FETCH_ORDER_GET_BYID = "FETCH_ORDER_GET_BYID";

export const FETCH_ORDER_GET_BYID_ORDER = "FETCH_ORDER_GET_BYID";

export const FETCH_ORDER_GET_BYID_ORDER_SUCCESS =
   "FETCH_ORDER_GET_BYID_ORDER_SUCCESS";
export const FETCH_ORDER_DELETE_SUCCESS = "FETCH_ORDER_DELETE_SUCCESS";
export const FETCH_ORDER_CREATE_SUCCESS = "FETCH_ORDER_CREATE_SUCCESS";
export const FETCH_ORDER_PATCH_SUCCESS = "FETCH_ORDER_PATCH_SUCCESS";
export const FETCH_ORDER_GET_BYID_SUCCESS = "FETCH_ORDER_PATCH_SUCCESS";

export const FETCH_ORDER_GET_BYID_ORDER_FAILED =
   "FETCH_ORDER_GET_BYID_ORDER_FAILED";
export const FETCH_ORDER_DELETE_FAILED = "FETCH_ORDER_DELETE_FAILED";
export const FETCH_ORDER_CREATE_FAILED = "FETCH_ORDER_CREATE_FAILED";
export const FETCH_ORDER_PATCH_FAILED = "FETCH_ORDER_PATCH_FAILED";
export const FETCH_ORDER_GET_BYID_FAILED = "FETCH_ORDER_GET_BYID_FAILED";
