export const FETCH_ORDER = "FETCH_ORDER";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAILED = "FETCH_ORDER_FAILED";

export const FETCH_ORDER_GET_BYID_ACCOUNT_SUCCESS =
   "FETCH_ORDER_GET_BYID_ACCOUNT_SUCCESS";
export const FETCH_ORDER_GET_BYID_ACCOUNT_FAILED =
   "FETCH_ORDER_GET_BYID_ACCOUNT_FAILED";

export const FETCH_ORDER_CREATE_SUCCESS = "FETCH_ORDER_CREATE_SUCCESS";
export const FETCH_ORDER_CREATE_FAILED = "FETCH_ORDER_CREATE_FAILED";

export const FETCH_ORDER_GET_BYID_SUCCESS = "FETCH_ORDER_PATCH_SUCCESS";
export const FETCH_ORDER_GET_BYID_FAILED = "FETCH_ORDER_GET_BYID_FAILED";

export const FETCH_ORDER_DELETE_SUCCESS = "FETCH_ORDER_DELETE_SUCCESS";
export const FETCH_ORDER_DELETE_FAILED = "FETCH_ORDER_DELETE_FAILED";

export const FETCH_ORDER_PATCH_SUCCESS = "FETCH_ORDER_PATCH_SUCCESS";
export const FETCH_ORDER_PATCH_FAILED = "FETCH_ORDER_PATCH_FAILED";

export const FETCH_GET_LINK_PAYMENT_SUCCESS = "FETCH_GET_LINK_PAYMENT_SUCCESS";
export const FETCH_GET_LINK_PAYMENT_FAILED = "FETCH_GET_LINK_PAYMENT_FAILED";

export const FETCH_ORDER_BY_EMAIL_SUCCESS = "FETCH_ORDER_BY_EMAIL_SUCCESS";
export const FETCH_ORDER_BY_EMAIL_FAILED = "FETCH_ORDER_BY_EMAIL_FAILED";
