export const FETCH_POST = "FETCH_POST";

export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";

export const FETCH_POST_FAILED = "FETCH_POST_FAILED";

export const FETCH_POST_SEARCH = "FETCH_POST_SEARCH";

export const FETCH_POST_SEARCH_SUCCESS = "FETCH_POST_SEARCH_SUCCESS";

export const FETCH_POST_SEARCH_FAILED = "FETCH_POST_SEARCH_FAILED";

export const FETCH_POST_GET_BYID = "FETCH_POST_GET_BYID";

export const FETCH_POST_GET_BYID_SUCCESS = "FETCH_POST_GET_BYID_SUCCESS";

export const FETCH_POST_GET_BYID_FAILED = "FETCH_POST_GET_BYID_FAILED";

export const VOTE_POST = "VOTE_POST";

export const VOTE_POST_SUCCESS = "VOTE_POST_SUCCESS";

export const VOTE_POST_FAILED = "VOTE_POST_FAILED";
