export const FETCH_TIMELINE_GET_BYID_TOUR = "FETCH_TIMELINE_GET_BYID_TOUR";

export const FETCH_TIMELINE_GET_BYID_TOUR_SUCCESS =
   "FETCH_TIMELINE_GET_BYID_TOUR_SUCCESS";

export const FETCH_TIMELINE_GET_BYID_TOUR_FAILED =
   "FETCH_TIMELINE_GET_BYID_TOUR_FAILED";
