export const FETCH_SCHEDULE = "FETCH_SCHEDULE";
export const FETCH_SCHEDULE_SUCCESS = "FETCH_SCHEDULE_SUCCESS";
export const FETCH_SCHEDULE_FAILED = "FETCH_SCHEDULE_FAILED";

export const FETCH_SCHEDULE_GET_BYID = "FETCH_SCHEDULE_GET_BYID";
export const FETCH_SCHEDULE_GET_BYID_SUCCESS =
   "FETCH_SCHEDULE_GET_BYID_SUCCESS";
export const FETCH_SCHEDULE_GET_BYID_FAILED = "FETCH_SCHEDULE_GET_BYID_FAILED";

export const FETCH_SCHEDULE_DELETE_SUCCESS = "FETCH_SCHEDULE_DELETE_SUCCESS";
export const FETCH_SCHEDULE_CREATE_SUCCESS = "FETCH_SCHEDULE_CREATE_SUCCESS";
export const FETCH_SCHEDULE_PATCH_SUCCESS = "FETCH_SCHEDULE_PATCH_SUCCESS";

export const FETCH_SCHEDULE_DELETE_FAILED = "FETCH_SCHEDULE_DELETE_FAILED";
export const FETCH_SCHEDULE_CREATE_FAILED = "FETCH_SCHEDULE_CREATE_FAILED";
export const FETCH_SCHEDULE_PATCH_FAILED = "FETCH_SCHEDULE_PATCH_FAILED";
