export const FETCH_TOUR = "FETCH_TOUR";
export const FETCH_TOUR_SUCCESS = "FETCH_TOUR_SUCCESS";
export const FETCH_TOUR_FAILED = "FETCH_TOUR_FAILED";

export const FETCH_TOUR_GET_BYID_SUCCESS = "FETCH_TOUR_GET_BYID_SUCCESS";
export const FETCH_TOUR_GET_BYID_FAILED = "FETCH_TOUR_GET_BYID_FAILED";

export const FETCH_TOUR_DELETE_SUCCESS = "FETCH_TOUR_DELETE_SUCCESS";
export const FETCH_TOUR_CREATE_SUCCESS = "FETCH_TOUR_CREATE_SUCCESS";
export const FETCH_TOUR_PATCH_SUCCESS = "FETCH_TOUR_PATCH_SUCCESS";

export const FETCH_TOUR_DELETE_FAILED = "FETCH_TOUR_DELETE_FAILED";
export const FETCH_TOUR_CREATE_FAILED = "FETCH_TOUR_CREATE_FAILED";
export const FETCH_TOUR_PATCH_FAILED = "FETCH_TOUR_PATCH_FAILED";

export const FETCH_TOUR_IMAGE = "FETCH_TOUR_IMAGE";
export const FETCH_TOUR_IMAGE_SUCCESS = "FETCH_TOUR_IMAGE_SUCCESS";
export const FETCH_TOUR_IMAGE_FAILED = "FETCH_TOUR_IMAGE_FAILED";
