export const FETCH_TOUR_IMAGE = "FETCH_TOUR_IMAGE";
// export const FETCH_TOUR_IMAGE_SUCCESS = "FETCH_TOUR_IMAGE_SUCCESS";
// export const FETCH_TOUR_IMAGE_FAILED = "FETCH_TOUR_IMAGE_FAILED";

export const FETCH_TOUR_IMAGE_DELETE_SUCCESS =
   "FETCH_TOUR_IMAGE_DELETE_SUCCESS";
export const FETCH_TOUR_IMAGE_CREATE_SUCCESS =
   "FETCH_TOUR_IMAGE_CREATE_SUCCESS";
export const FETCH_TOUR_UPLOAD_IMAGE_SUCCESS = "FETCH_TOUR_IMAGE_PATCH_SUCCESS";

export const FETCH_TOUR_IMAGE_DELETE_FAILED = "FETCH_TOUR_IMAGE_DELETE_FAILED";
export const FETCH_TOUR_IMAGE_CREATE_FAILED = "FETCH_TOUR_IMAGE_CREATE_FAILED";
export const FETCH_TOUR_UPLOAD_IMAGE_FAILED =
   "FETCH_TOUR_IMAGE_UPLOAD_IMAGE_FAILED";
