export const FETCH_ACCOUNT = "FETCH_ACCOUNT";
export const FETCH_ACCOUNT_SUCCESS = "FETCH_ACCOUNT_SUCCESS";
export const FETCH_ACCOUNT_FAILED = "FETCH_ACCOUNT_FAILED";

export const FETCH_ACCOUNT_GET_BYID_SUCCESS = "FETCH_ACCOUNT_GET_BYID_SUCCESS";
export const FETCH_ACCOUNT_GET_BYID_FAILED = "FETCH_ACCOUNT_GET_BYID_FAILED";

export const FETCH_ACCOUNT_DELETE_SUCCESS = "FETCH_ACCOUNT_DELETE_SUCCESS";
export const FETCH_ACCOUNT_CREATE_SUCCESS = "FETCH_ACCOUNT_CREATE_SUCCESS";
export const FETCH_ACCOUNT_PATCH_SUCCESS = "FETCH_ACCOUNT_PATCH_SUCCESS";

export const FETCH_ACCOUNT_DELETE_FAILED = "FETCH_ACCOUNT_DELETE_FAILED";
export const FETCH_ACCOUNT_CREATE_FAILED = "FETCH_ACCOUNT_CREATE_FAILED";
export const FETCH_ACCOUNT_PATCH_FAILED = "FETCH_ACCOUNT_PATCH_FAILED";

export const FETCH_ACCOUNT_IMAGE = "FETCH_ACCOUNT_IMAGE";
export const FETCH_ACCOUNT_IMAGE_SUCCESS = "FETCH_ACCOUNT_IMAGE_SUCCESS";
export const FETCH_ACCOUNT_IMAGE_FAILED = "FETCH_ACCOUNT_IMAGE_FAILED";

export const FETCH_ACCOUNT_IMAGE_DELETE_SUCCESS =
   "FETCH_ACCOUNT_IMAGE_DELETE_SUCCESS";
export const FETCH_ACCOUNT_IMAGE_DELETE_FAILED =
   "FETCH_ACCOUNT_IMAGE_DELETE_FAILED";
