export const FETCH_CONFIG = "FETCH_CONFIG";
export const FETCH_CONFIG_SUCCESS = "FETCH_CONFIG_SUCCESS";
export const FETCH_CONFIG_FAILED = "FETCH_CONFIG_FAILED";

export const FETCH_CONFIG_GET_BYID_SUCCESS = "FETCH_CONFIG_GET_BYID_SUCCESS";
export const FETCH_CONFIG_GET_BYID_FAILED = "FETCH_CONFIG_GET_BYID_FAILED";

export const FETCH_CONFIG_GET_BY_INFOTYPE_SUCCESS =
   "FETCH_CONFIG_GET_BY_INFOTYPE_SUCCESS";
export const FETCH_CONFIG_GET_BY_INFOTYPE_FAILED =
   "FETCH_CONFIG_GET_BY_INFOTYPE_FAILED";

export const FETCH_CONFIG_DELETE_SUCCESS = "FETCH_CONFIG_DELETE_SUCCESS";
export const FETCH_CONFIG_CREATE_SUCCESS = "FETCH_CONFIG_CREATE_SUCCESS";
export const FETCH_CONFIG_PATCH_SUCCESS = "FETCH_CONFIG_PATCH_SUCCESS";

export const FETCH_CONFIG_DELETE_FAILED = "FETCH_CONFIG_DELETE_FAILED";
export const FETCH_CONFIG_CREATE_FAILED = "FETCH_CONFIG_CREATE_FAILED";
export const FETCH_CONFIG_PATCH_FAILED = "FETCH_CONFIG_PATCH_FAILED";

export const FETCH_CONFIG_IMAGE = "FETCH_CONFIG_IMAGE";
export const FETCH_CONFIG_IMAGE_SUCCESS = "FETCH_CONFIG_IMAGE_SUCCESS";
export const FETCH_CONFIG_IMAGE_FAILED = "FETCH_CONFIG_IMAGE_FAILED";

export const FETCH_CONFIG_IMAGE_DELETE_SUCCESS =
   "FETCH_CONFIG_IMAGE_DELETE_SUCCESS";
export const FETCH_CONFIG_IMAGE_DELETE_FAILED =
   "FETCH_CONFIG_IMAGE_DELETE_FAILED";
