export const FETCH_GENERAL = "FETCH_GENERAL";
export const FETCH_GENERAL_SUCCESS = "FETCH_GENERAL_SUCCESS";
export const FETCH_GENERAL_FAILED = "FETCH_GENERAL_FAILED";

export const FETCH_GENERAL_GET_BYID_SUCCESS = "FETCH_GENERAL_GET_BYID_SUCCESS";
export const FETCH_GENERAL_GET_BYID_FAILED = "FETCH_GENERAL_GET_BYID_FAILED";

export const FETCH_GENERAL_DELETE_SUCCESS = "FETCH_GENERAL_DELETE_SUCCESS";
export const FETCH_GENERAL_CREATE_SUCCESS = "FETCH_GENERAL_CREATE_SUCCESS";
export const FETCH_GENERAL_PATCH_SUCCESS = "FETCH_GENERAL_PATCH_SUCCESS";

export const FETCH_GENERAL_DELETE_FAILED = "FETCH_GENERAL_DELETE_FAILED";
export const FETCH_GENERAL_CREATE_FAILED = "FETCH_GENERAL_CREATE_FAILED";
export const FETCH_GENERAL_PATCH_FAILED = "FETCH_GENERAL_PATCH_FAILED";

export const FETCH_GENERAL_IMAGE = "FETCH_GENERAL_IMAGE";
export const FETCH_GENERAL_IMAGE_SUCCESS = "FETCH_GENERAL_IMAGE_SUCCESS";
export const FETCH_GENERAL_IMAGE_FAILED = "FETCH_GENERAL_IMAGE_FAILED";

export const FETCH_GENERAL_IMAGE_DELETE_SUCCESS =
   "FETCH_GENERAL_IMAGE_DELETE_SUCCESS";
export const FETCH_GENERAL_IMAGE_DELETE_FAILED =
   "FETCH_GENERAL_IMAGE_DELETE_FAILED";
