export const FETCH_IMAGE_DELETE_SUCCESS = "FETCH_IMAGE_DELETE_SUCCESS";
export const FETCH_UPLOAD_IMAGE_FAILED = "FETCH_IMAGE_UPLOAD_IMAGE_FAILED";
export const FETCH_IMAGE_CREATE_SUCCESS = "FETCH_IMAGE_CREATE_SUCCESS";
export const FETCH_UPLOAD_IMAGE_SUCCESS = "FETCH_IMAGE_PATCH_SUCCESS";
export const FETCH_IMAGE_GET_BYID = "FETCH_IMAGE_GET_BYID";

export const FETCH_IMAGE_DELETE_FAILED = "FETCH_IMAGE_DELETE_FAILED";
export const FETCH_IMAGE_CREATE_FAILED = "FETCH_IMAGE_CREATE_FAILED";
export const FETCH_IMAGE_GET_BYID_TOUR_SUCCESS =
   "FETCH_IMAGE_GET_BYID_TOUR_SUCCESS";
export const FETCH_IMAGE_GET_BYID_TOUR_FAILED =
   "FETCH_IMAGE_GET_BYID_TOUR_FAILED";

export const FETCH_IMAGE_GET_BYID_POST_SUCCESS =
   "FETCH_IMAGE_GET_BYID_POST_SUCCESS";
export const FETCH_IMAGE_GET_BYID_POST_FAILED =
   "FETCH_IMAGE_GET_BYID_POST_FAILED";
