export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION";
export const FETCH_NOTIFICATION_SUCCESS = "FETCH_NOTIFICATION_SUCCESS";
export const FETCH_NOTIFICATION_FAILED = "FETCH_NOTIFICATION_FAILED";

export const FETCH_NOTIFICATION_GET_BYID_SUCCESS =
   "FETCH_NOTIFICATION_GET_BYID_SUCCESS";
export const FETCH_NOTIFICATION_GET_BYID_FAILED =
   "FETCH_NOTIFICATION_GET_BYID_FAILED";

export const FETCH_NOTIFICATION_DELETE_SUCCESS =
   "FETCH_NOTIFICATION_DELETE_SUCCESS";
export const FETCH_NOTIFICATION_CREATE_SUCCESS =
   "FETCH_NOTIFICATION_CREATE_SUCCESS";
export const FETCH_NOTIFICATION_PATCH_SUCCESS =
   "FETCH_NOTIFICATION_PATCH_SUCCESS";

export const FETCH_NOTIFICATION_DELETE_FAILED =
   "FETCH_NOTIFICATION_DELETE_FAILED";
export const FETCH_NOTIFICATION_CREATE_FAILED =
   "FETCH_NOTIFICATION_CREATE_FAILED";
export const FETCH_NOTIFICATION_PATCH_FAILED =
   "FETCH_NOTIFICATION_PATCH_FAILED";

export const FETCH_NOTIFICATION_IMAGE = "FETCH_NOTIFICATION_IMAGE";
export const FETCH_NOTIFICATION_IMAGE_SUCCESS =
   "FETCH_NOTIFICATION_IMAGE_SUCCESS";
export const FETCH_NOTIFICATION_IMAGE_FAILED =
   "FETCH_NOTIFICATION_IMAGE_FAILED";

export const FETCH_NOTIFICATION_IMAGE_DELETE_SUCCESS =
   "FETCH_NOTIFICATION_IMAGE_DELETE_SUCCESS";
export const FETCH_NOTIFICATION_IMAGE_DELETE_FAILED =
   "FETCH_NOTIFICATION_IMAGE_DELETE_FAILED";
