export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAILED = "FETCH_NOTIFICATIONS_FAILED";

export const FETCH_NOTIFICATIONS_GET_BYID_SUCCESS =
   "FETCH_NOTIFICATIONS_GET_BYID_SUCCESS";
export const FETCH_NOTIFICATIONS_GET_BYID_FAILED =
   "FETCH_NOTIFICATIONS_GET_BYID_FAILED";

export const FETCH_NOTIFICATIONS_DELETE_SUCCESS =
   "FETCH_NOTIFICATIONS_DELETE_SUCCESS";
export const FETCH_NOTIFICATIONS_CREATE_SUCCESS =
   "FETCH_NOTIFICATIONS_CREATE_SUCCESS";
export const FETCH_NOTIFICATIONS_PATCH_SUCCESS =
   "FETCH_NOTIFICATIONS_PATCH_SUCCESS";

export const FETCH_NOTIFICATIONS_DELETE_FAILED =
   "FETCH_NOTIFICATIONS_DELETE_FAILED";
export const FETCH_NOTIFICATIONS_CREATE_FAILED =
   "FETCH_NOTIFICATIONS_CREATE_FAILED";
export const FETCH_NOTIFICATIONS_PATCH_FAILED =
   "FETCH_NOTIFICATIONS_PATCH_FAILED";

export const FETCH_NOTIFICATIONS_IMAGE = "FETCH_NOTIFICATIONS_IMAGE";
export const FETCH_NOTIFICATIONS_IMAGE_SUCCESS =
   "FETCH_NOTIFICATIONS_IMAGE_SUCCESS";
export const FETCH_NOTIFICATIONS_IMAGE_FAILED =
   "FETCH_NOTIFICATIONS_IMAGE_FAILED";

export const FETCH_NOTIFICATIONS_IMAGE_DELETE_SUCCESS =
   "FETCH_NOTIFICATIONS_IMAGE_DELETE_SUCCESS";
export const FETCH_NOTIFICATIONS_IMAGE_DELETE_FAILED =
   "FETCH_NOTIFICATIONS_IMAGE_DELETE_FAILED";
