export const FETCH_POST = "FETCH_POST";
export const FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POST_FAILED = "FETCH_POST_FAILED";

export const FETCH_POST_GET_BYID_SUCCESS = "FETCH_POST_GET_BYID_SUCCESS";
export const FETCH_POST_GET_BYID_FAILED = "FETCH_POST_GET_BYID_FAILED";

export const FETCH_POST_DELETE_SUCCESS = "FETCH_POST_DELETE_SUCCESS";
export const FETCH_POST_CREATE_SUCCESS = "FETCH_POST_CREATE_SUCCESS";
export const FETCH_POST_PATCH_SUCCESS = "FETCH_POST_PATCH_SUCCESS";

export const FETCH_POST_DELETE_FAILED = "FETCH_POST_DELETE_FAILED";
export const FETCH_POST_CREATE_FAILED = "FETCH_POST_CREATE_FAILED";
export const FETCH_POST_PATCH_FAILED = "FETCH_POST_PATCH_FAILED";

export const FETCH_POST_IMAGE = "FETCH_POST_IMAGE";
export const FETCH_POST_IMAGE_SUCCESS = "FETCH_POST_IMAGE_SUCCESS";
export const FETCH_POST_IMAGE_FAILED = "FETCH_POST_IMAGE_FAILED";

export const FETCH_POST_IMAGE_DELETE_SUCCESS =
   "FETCH_POST_IMAGE_DELETE_SUCCESS";
export const FETCH_POST_IMAGE_DELETE_FAILED = "FETCH_POST_IMAGE_DELETE_FAILED";
