require("dotenv").config();

export const FETCH_REPORT = "FETCH_REPORT";
export const FETCH_REPORT_SUCCESS = "FETCH_REPORT_SUCCESS";
export const FETCH_REPORT_FAILED = "FETCH_REPORT_FAILED";

//reportNumberOfTourists
export const FETCH_REPORT_NUMBER_OF_TOURISTS =
   "FETCH_REPORT_NUMBER_OF_TOURISTS";
export const FETCH_REPORT_NUMBER_OF_TOURISTS_SUCCESS =
   "FETCH_REPORT_NUMBER_OF_TOURISTS_SUCCESS";
export const FETCH_REPORT_NUMBER_OF_TOURISTS_FAILED =
   "FETCH_REPORT_NUMBER_OF_TOURISTS_FAILED";

//reportNumberPeopleFollowDestination
export const FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION =
   "FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION";
export const FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION_SUCCESS =
   "FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION_SUCCESS";
export const FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION_FAILED =
   "FETCH_REPORT_NUMBER_PEOPLE_FOLLOW_DESTINATION_FAILED";

//reportRevenueFollowMonth
export const FETCH_REPORT_REVENUE_FOLLOW_MONTH =
   "FETCH_REPORT_REVENUE_FOLLOW_MONTH";
export const FETCH_REPORT_REVENUE_FOLLOW_MONTH_SUCCESS =
   "FETCH_REPORT_REVENUE_FOLLOW_MONTH_SUCCESS";
export const FETCH_REPORT_REVENUE_FOLLOW_MONTH_FAILED =
   "FETCH_REPORT_REVENUE_FOLLOW_MONTH_FAILED";
