export const FETCH_SERVICE = "FETCH_SERVICE";
export const FETCH_SERVICE_SUCCESS = "FETCH_SERVICE_SUCCESS";
export const FETCH_SERVICE_FAILED = "FETCH_SERVICE_FAILED";

export const FETCH_SERVICE_GET_BYID_SUCCESS = "FETCH_SERVICE_GET_BYID_SUCCESS";
export const FETCH_SERVICE_GET_BYID_FAILED = "FETCH_SERVICE_GET_BYID_FAILED";

export const FETCH_SERVICE_DELETE_SUCCESS = "FETCH_SERVICE_DELETE_SUCCESS";
export const FETCH_SERVICE_CREATE_SUCCESS = "FETCH_SERVICE_CREATE_SUCCESS";
export const FETCH_SERVICE_PATCH_SUCCESS = "FETCH_SERVICE_PATCH_SUCCESS";

export const FETCH_SERVICE_DELETE_FAILED = "FETCH_SERVICE_DELETE_FAILED";
export const FETCH_SERVICE_CREATE_FAILED = "FETCH_SERVICE_CREATE_FAILED";
export const FETCH_SERVICE_PATCH_FAILED = "FETCH_SERVICE_PATCH_FAILED";

export const FETCH_SERVICE_IMAGE = "FETCH_SERVICE_IMAGE";
export const FETCH_SERVICE_IMAGE_SUCCESS = "FETCH_SERVICE_IMAGE_SUCCESS";
export const FETCH_SERVICE_IMAGE_FAILED = "FETCH_SERVICE_IMAGE_FAILED";

export const FETCH_SERVICE_IMAGE_DELETE_SUCCESS =
   "FETCH_SERVICE_IMAGE_DELETE_SUCCESS";
export const FETCH_SERVICE_IMAGE_DELETE_FAILED =
   "FETCH_SERVICE_IMAGE_DELETE_FAILED";
