export const FETCH_TAG = "FETCH_TAG";
export const FETCH_TAG_SUCCESS = "FETCH_TAG_SUCCESS";
export const FETCH_TAG_FAILED = "FETCH_TAG_FAILED";

export const FETCH_TAG_GET_BYID_SUCCESS = "FETCH_TAG_GET_BYID_SUCCESS";
export const FETCH_TAG_GET_BYID_FAILED = "FETCH_TAG_GET_BYID_FAILED";

export const FETCH_TAG_DELETE_SUCCESS = "FETCH_TAG_DELETE_SUCCESS";
export const FETCH_TAG_CREATE_SUCCESS = "FETCH_TAG_CREATE_SUCCESS";
export const FETCH_TAG_PATCH_SUCCESS = "FETCH_TAG_PATCH_SUCCESS";

export const FETCH_TAG_DELETE_FAILED = "FETCH_TAG_DELETE_FAILED";
export const FETCH_TAG_CREATE_FAILED = "FETCH_TAG_CREATE_FAILED";
export const FETCH_TAG_PATCH_FAILED = "FETCH_TAG_PATCH_FAILED";

export const FETCH_TAG_IMAGE = "FETCH_TAG_IMAGE";
export const FETCH_TAG_IMAGE_SUCCESS = "FETCH_TAG_IMAGE_SUCCESS";
export const FETCH_TAG_IMAGE_FAILED = "FETCH_TAG_IMAGE_FAILED";

export const FETCH_TAG_IMAGE_DELETE_SUCCESS = "FETCH_TAG_IMAGE_DELETE_SUCCESS";
export const FETCH_TAG_IMAGE_DELETE_FAILED = "FETCH_TAG_IMAGE_DELETE_FAILED";
