export const FETCH_TIMELINE = "FETCH_TIMELINE";
export const FETCH_TIMELINE_SUCCESS = "FETCH_TIMELINE_SUCCESS";
export const FETCH_TIMELINE_FAILED = "FETCH_TIMELINE_FAILED";

export const FETCH_TIMELINE_GET_BYID_SUCCESS =
   "FETCH_TIMELINE_GET_BYID_SUCCESS";
export const FETCH_TIMELINE_GET_BYID_FAILED = "FETCH_TIMELINE_GET_BYID_FAILED";

export const FETCH_TIMELINE_DELETE_SUCCESS = "FETCH_TIMELINE_DELETE_SUCCESS";
export const FETCH_TIMELINE_CREATE_SUCCESS = "FETCH_TIMELINE_CREATE_SUCCESS";
export const FETCH_TIMELINE_PATCH_SUCCESS = "FETCH_TIMELINE_PATCH_SUCCESS";

export const FETCH_TIMELINE_DELETE_FAILED = "FETCH_TIMELINE_DELETE_FAILED";
export const FETCH_TIMELINE_CREATE_FAILED = "FETCH_TIMELINE_CREATE_FAILED";
export const FETCH_TIMELINE_PATCH_FAILED = "FETCH_TIMELINE_PATCH_FAILED";

export const FETCH_TIMELINE_IMAGE = "FETCH_TIMELINE_IMAGE";
export const FETCH_TIMELINE_IMAGE_SUCCESS = "FETCH_TIMELINE_IMAGE_SUCCESS";
export const FETCH_TIMELINE_IMAGE_FAILED = "FETCH_TIMELINE_IMAGE_FAILED";

export const FETCH_TIMELINE_IMAGE_DELETE_SUCCESS =
   "FETCH_TIMELINE_IMAGE_DELETE_SUCCESS";
export const FETCH_TIMELINE_IMAGE_DELETE_FAILED =
   "FETCH_TIMELINE_IMAGE_DELETE_FAILED";
